# File : .pep8speaks.yml

scanner:
    diff_only: True  # Errors caused by only the patch are shown

pycodestyle:
    ignore:  # Errors and warnings to ignore
        - E402  # module level import not at top of file
        - W504  # line break after binary operator
        - E123  # closing bracket does not match indentation of opening bracket's line
